app_group:
  - read:
      path: /apps/connect.eda.nokia.com
      method: GET

patch:
  - update:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits/{name}
      method: PATCH
  - update:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces/{name}
      method: PATCH
  - update:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables/{name}
      method: PATCH
  - update:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits/{name}/_revs
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces/{name}/_revs
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables/{name}/_revs
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/connect.eda.nokia.com/v1
      method: GET

resource_topology:
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits/{name}/_topology
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces/{name}/_topology
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables/{name}/_topology
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits/{name}
      method: DELETE
  - delete:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces/{name}
      method: DELETE
  - delete:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables/{name}
      method: DELETE
  - delete:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/connect.eda.nokia.com/v1/_ui/{pathname}
      method: GET

com.nokia.eda.connect.v1.connect_audit:
  - create:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits
      method: POST
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits/{name}
      method: GET
  - update:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits/{name}
      method: PUT

com.nokia.eda.connect.v1.connect_audit_list:
  - read:
      path: /apps/connect.eda.nokia.com/v1/connectaudits
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits
      method: GET
  - delete:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits
      method: DELETE

com.nokia.eda.connect.v1.connect_audit_deleted_resources:
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectaudits/_deleted
      method: GET

com.nokia.eda.connect.v1.connect_interface:
  - create:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces
      method: POST
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces/{name}
      method: GET
  - update:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces/{name}
      method: PUT

com.nokia.eda.connect.v1.connect_interface_list:
  - read:
      path: /apps/connect.eda.nokia.com/v1/connectinterfaces
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces
      method: GET
  - delete:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces
      method: DELETE

com.nokia.eda.connect.v1.connect_interface_deleted_resources:
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectinterfaces/_deleted
      method: GET

com.nokia.eda.connect.v1.connect_plugin:
  - create:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins
      method: POST
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins/{name}
      method: GET
  - update:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins/{name}
      method: PUT

com.nokia.eda.connect.v1.connect_plugin_actionable:
  - create:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables
      method: POST
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables/{name}
      method: GET
  - update:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables/{name}
      method: PUT

com.nokia.eda.connect.v1.connect_plugin_actionable_list:
  - read:
      path: /apps/connect.eda.nokia.com/v1/connectpluginactionables
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables
      method: GET
  - delete:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables
      method: DELETE

com.nokia.eda.connect.v1.connect_plugin_actionable_deleted_resources:
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectpluginactionables/_deleted
      method: GET

com.nokia.eda.connect.v1.connect_plugin_list:
  - read:
      path: /apps/connect.eda.nokia.com/v1/connectplugins
      method: GET
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins
      method: GET
  - delete:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins
      method: DELETE

com.nokia.eda.connect.v1.connect_plugin_deleted_resources:
  - read:
      path: /apps/connect.eda.nokia.com/v1/namespaces/{namespace}/connectplugins/_deleted
      method: GET

totalPaths: 27
totalSchemas: 48
usedSchemas: 19
unusedSchemas: 29
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoElemMetadata
  - TopoLinkEndpoint
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeState
  - TopoSchema
  - Topology
  - com.nokia.eda.connect.v1.ConnectAudit_DeletedResourceEntry
  - com.nokia.eda.connect.v1.ConnectAudit_metadata
  - com.nokia.eda.connect.v1.ConnectInterface_DeletedResourceEntry
  - com.nokia.eda.connect.v1.ConnectInterface_metadata
  - com.nokia.eda.connect.v1.ConnectPluginActionable_DeletedResourceEntry
  - com.nokia.eda.connect.v1.ConnectPluginActionable_metadata
  - com.nokia.eda.connect.v1.ConnectPlugin_DeletedResourceEntry
  - com.nokia.eda.connect.v1.ConnectPlugin_metadata
